###############################################################################
# Created by write_sdc
# Sat Apr 30 00:20:09 2022
###############################################################################
current_design GPIO
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 10.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_input[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_input[10]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_input[11]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_input[12]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_input[13]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_input[14]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_input[15]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_input[16]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_input[17]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_input[18]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_input[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_input[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_input[3]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_input[4]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_input[5]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_input[6]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_input[7]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_input[8]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_input[9]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_input[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_input[10]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_input[11]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_input[12]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_input[13]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_input[14]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_input[15]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_input[16]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_input[17]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_input[18]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_input[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_input[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_input[3]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_input[4]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_input[5]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_input[6]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_input[7]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_input[8]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_input[9]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_address[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_address[10]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_address[11]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_address[12]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_address[13]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_address[14]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_address[15]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_address[16]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_address[17]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_address[18]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_address[19]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_address[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_address[20]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_address[21]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_address[22]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_address[23]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_address[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_address[3]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_address[4]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_address[5]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_address[6]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_address[7]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_address[8]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_address[9]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[10]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[11]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[12]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[13]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[14]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[15]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[16]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[17]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[18]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[19]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[20]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[21]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[22]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[23]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[24]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[25]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[26]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[27]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[28]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[29]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[30]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[31]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[3]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[4]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[5]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[6]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[7]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[8]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataIn[9]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_oe}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_we}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rst}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_oe[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_oe[10]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_oe[11]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_oe[12]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_oe[13]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_oe[14]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_oe[15]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_oe[16]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_oe[17]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_oe[18]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_oe[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_oe[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_oe[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_oe[4]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_oe[5]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_oe[6]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_oe[7]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_oe[8]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_oe[9]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_output[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_output[10]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_output[11]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_output[12]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_output[13]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_output[14]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_output[15]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_output[16]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_output[17]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_output[18]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_output[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_output[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_output[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_output[4]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_output[5]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_output[6]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_output[7]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_output[8]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio0_output[9]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_oe[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_oe[10]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_oe[11]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_oe[12]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_oe[13]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_oe[14]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_oe[15]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_oe[16]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_oe[17]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_oe[18]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_oe[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_oe[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_oe[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_oe[4]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_oe[5]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_oe[6]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_oe[7]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_oe[8]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_oe[9]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_output[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_output[10]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_output[11]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_output[12]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_output[13]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_output[14]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_output[15]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_output[16]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_output[17]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_output[18]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_output[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_output[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_output[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_output[4]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_output[5]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_output[6]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_output[7]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_output[8]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio1_output[9]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_busy}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[10]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[11]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[12]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[13]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[14]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[15]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[16]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[17]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[18]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[19]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[20]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[21]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[22]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[23]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[24]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[25]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[26]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[27]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[28]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[29]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[30]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[31]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[4]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[5]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[6]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[7]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[8]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {peripheralBus_dataOut[9]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {requestOutput}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {peripheralBus_busy}]
set_load -pin_load 0.0334 [get_ports {requestOutput}]
set_load -pin_load 0.0334 [get_ports {gpio0_oe[18]}]
set_load -pin_load 0.0334 [get_ports {gpio0_oe[17]}]
set_load -pin_load 0.0334 [get_ports {gpio0_oe[16]}]
set_load -pin_load 0.0334 [get_ports {gpio0_oe[15]}]
set_load -pin_load 0.0334 [get_ports {gpio0_oe[14]}]
set_load -pin_load 0.0334 [get_ports {gpio0_oe[13]}]
set_load -pin_load 0.0334 [get_ports {gpio0_oe[12]}]
set_load -pin_load 0.0334 [get_ports {gpio0_oe[11]}]
set_load -pin_load 0.0334 [get_ports {gpio0_oe[10]}]
set_load -pin_load 0.0334 [get_ports {gpio0_oe[9]}]
set_load -pin_load 0.0334 [get_ports {gpio0_oe[8]}]
set_load -pin_load 0.0334 [get_ports {gpio0_oe[7]}]
set_load -pin_load 0.0334 [get_ports {gpio0_oe[6]}]
set_load -pin_load 0.0334 [get_ports {gpio0_oe[5]}]
set_load -pin_load 0.0334 [get_ports {gpio0_oe[4]}]
set_load -pin_load 0.0334 [get_ports {gpio0_oe[3]}]
set_load -pin_load 0.0334 [get_ports {gpio0_oe[2]}]
set_load -pin_load 0.0334 [get_ports {gpio0_oe[1]}]
set_load -pin_load 0.0334 [get_ports {gpio0_oe[0]}]
set_load -pin_load 0.0334 [get_ports {gpio0_output[18]}]
set_load -pin_load 0.0334 [get_ports {gpio0_output[17]}]
set_load -pin_load 0.0334 [get_ports {gpio0_output[16]}]
set_load -pin_load 0.0334 [get_ports {gpio0_output[15]}]
set_load -pin_load 0.0334 [get_ports {gpio0_output[14]}]
set_load -pin_load 0.0334 [get_ports {gpio0_output[13]}]
set_load -pin_load 0.0334 [get_ports {gpio0_output[12]}]
set_load -pin_load 0.0334 [get_ports {gpio0_output[11]}]
set_load -pin_load 0.0334 [get_ports {gpio0_output[10]}]
set_load -pin_load 0.0334 [get_ports {gpio0_output[9]}]
set_load -pin_load 0.0334 [get_ports {gpio0_output[8]}]
set_load -pin_load 0.0334 [get_ports {gpio0_output[7]}]
set_load -pin_load 0.0334 [get_ports {gpio0_output[6]}]
set_load -pin_load 0.0334 [get_ports {gpio0_output[5]}]
set_load -pin_load 0.0334 [get_ports {gpio0_output[4]}]
set_load -pin_load 0.0334 [get_ports {gpio0_output[3]}]
set_load -pin_load 0.0334 [get_ports {gpio0_output[2]}]
set_load -pin_load 0.0334 [get_ports {gpio0_output[1]}]
set_load -pin_load 0.0334 [get_ports {gpio0_output[0]}]
set_load -pin_load 0.0334 [get_ports {gpio1_oe[18]}]
set_load -pin_load 0.0334 [get_ports {gpio1_oe[17]}]
set_load -pin_load 0.0334 [get_ports {gpio1_oe[16]}]
set_load -pin_load 0.0334 [get_ports {gpio1_oe[15]}]
set_load -pin_load 0.0334 [get_ports {gpio1_oe[14]}]
set_load -pin_load 0.0334 [get_ports {gpio1_oe[13]}]
set_load -pin_load 0.0334 [get_ports {gpio1_oe[12]}]
set_load -pin_load 0.0334 [get_ports {gpio1_oe[11]}]
set_load -pin_load 0.0334 [get_ports {gpio1_oe[10]}]
set_load -pin_load 0.0334 [get_ports {gpio1_oe[9]}]
set_load -pin_load 0.0334 [get_ports {gpio1_oe[8]}]
set_load -pin_load 0.0334 [get_ports {gpio1_oe[7]}]
set_load -pin_load 0.0334 [get_ports {gpio1_oe[6]}]
set_load -pin_load 0.0334 [get_ports {gpio1_oe[5]}]
set_load -pin_load 0.0334 [get_ports {gpio1_oe[4]}]
set_load -pin_load 0.0334 [get_ports {gpio1_oe[3]}]
set_load -pin_load 0.0334 [get_ports {gpio1_oe[2]}]
set_load -pin_load 0.0334 [get_ports {gpio1_oe[1]}]
set_load -pin_load 0.0334 [get_ports {gpio1_oe[0]}]
set_load -pin_load 0.0334 [get_ports {gpio1_output[18]}]
set_load -pin_load 0.0334 [get_ports {gpio1_output[17]}]
set_load -pin_load 0.0334 [get_ports {gpio1_output[16]}]
set_load -pin_load 0.0334 [get_ports {gpio1_output[15]}]
set_load -pin_load 0.0334 [get_ports {gpio1_output[14]}]
set_load -pin_load 0.0334 [get_ports {gpio1_output[13]}]
set_load -pin_load 0.0334 [get_ports {gpio1_output[12]}]
set_load -pin_load 0.0334 [get_ports {gpio1_output[11]}]
set_load -pin_load 0.0334 [get_ports {gpio1_output[10]}]
set_load -pin_load 0.0334 [get_ports {gpio1_output[9]}]
set_load -pin_load 0.0334 [get_ports {gpio1_output[8]}]
set_load -pin_load 0.0334 [get_ports {gpio1_output[7]}]
set_load -pin_load 0.0334 [get_ports {gpio1_output[6]}]
set_load -pin_load 0.0334 [get_ports {gpio1_output[5]}]
set_load -pin_load 0.0334 [get_ports {gpio1_output[4]}]
set_load -pin_load 0.0334 [get_ports {gpio1_output[3]}]
set_load -pin_load 0.0334 [get_ports {gpio1_output[2]}]
set_load -pin_load 0.0334 [get_ports {gpio1_output[1]}]
set_load -pin_load 0.0334 [get_ports {gpio1_output[0]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[31]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[30]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[29]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[28]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[27]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[26]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[25]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[24]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[23]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[22]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[21]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[20]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[19]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[18]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[17]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[16]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[15]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[14]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[13]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[12]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[11]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[10]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[9]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[8]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[7]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[6]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[5]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[4]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[3]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[2]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[1]}]
set_load -pin_load 0.0334 [get_ports {peripheralBus_dataOut[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_oe}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_we}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {rst}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio0_input[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio0_input[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio0_input[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio0_input[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio0_input[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio0_input[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio0_input[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio0_input[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio0_input[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio0_input[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio0_input[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio0_input[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio0_input[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio0_input[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio0_input[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio0_input[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio0_input[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio0_input[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio0_input[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio1_input[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio1_input[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio1_input[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio1_input[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio1_input[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio1_input[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio1_input[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio1_input[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio1_input[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio1_input[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio1_input[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio1_input[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio1_input[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio1_input[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio1_input[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio1_input[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio1_input[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio1_input[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio1_input[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_address[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_address[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_address[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_address[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_address[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_address[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_address[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_address[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_address[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_address[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_address[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_address[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_address[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_address[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_address[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_address[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_address[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_address[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_address[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_address[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_address[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_address[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_address[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_address[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {peripheralBus_dataIn[0]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_fanout 5.0000 [current_design]
